/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mythicaguide;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    
    public String diretorio;
    public Connection getConexao;
    
    public Cadastro(String raizDiretorio, Connection conexao) {
        initComponents();
        diretorio = raizDiretorio;
        this.getConexao = conexao;
        this.setLocationRelativeTo(null);
        loadingCadastro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomePessoa = new javax.swing.JTextField();
        nomeUsuário = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nascimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numeroCelular = new javax.swing.JTextField();
        whatsapp = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        senha = new javax.swing.JPasswordField();
        loadingCadastro = new javax.swing.JProgressBar();
        btnFecharAba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cinzel Decorative", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro MythicaGuide");

        jLabel2.setFont(new java.awt.Font("Cinzel Decorative", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome *:");

        nomePessoa.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        nomePessoa.setForeground(new java.awt.Color(0, 153, 153));
        nomePessoa.setToolTipText("");

        nomeUsuário.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        nomeUsuário.setForeground(new java.awt.Color(0, 153, 153));
        nomeUsuário.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Cinzel Decorative", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuário *:");

        jLabel4.setFont(new java.awt.Font("Cinzel Decorative", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Email *:");

        email.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(0, 153, 153));
        email.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Cinzel Decorative", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nascimento:");

        nascimento.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        nascimento.setForeground(new java.awt.Color(0, 153, 153));
        nascimento.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Cinzel Decorative", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Número:");

        numeroCelular.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        numeroCelular.setForeground(new java.awt.Color(0, 153, 153));
        numeroCelular.setToolTipText("");

        whatsapp.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        whatsapp.setForeground(new java.awt.Color(0, 102, 102));
        whatsapp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jLabel7.setFont(new java.awt.Font("Cinzel Decorative", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("WhatsApp:");

        jLabel8.setFont(new java.awt.Font("Cinzel Decorative", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Senha *:");

        cadastrar.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(0, 153, 153));
        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mythicaguide/resouces/icons8-cadastro-32.png"))); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n \"Descubra o poder do MythicaGuide, o seu guia definitivo para aprimorar suas campanhas de RPG de mesa. Com uma interface intuitiva e recursos de última geração, nosso sistema web irá transportá-lo para mundos repletos de mistérios e aventuras. Explore cenários detalhados, crie personagens cativantes e mergulhe em narrativas imersivas que desafiarão sua imaginação. Com ferramentas poderosas ao seu alcance, como geradores de missões, bibliotecas de monstros e trilhas sonoras envolventes, você se tornará o mestre da sua própria jornada. Prepare-se para batalhas épicas, enigmas intrigantes e reviravoltas surpreendentes. Deixe o MythicaGuide guiar você em uma experiência de RPG inigualável, onde a magia se torna realidade e a diversão nunca tem fim.\"");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextArea1);

        senha.setFont(new java.awt.Font("Cinzel Decorative", 1, 12)); // NOI18N
        senha.setForeground(new java.awt.Color(0, 153, 153));
        senha.setToolTipText("");

        loadingCadastro.setBackground(new java.awt.Color(0, 204, 204));
        loadingCadastro.setFont(new java.awt.Font("Cinzel Decorative", 1, 10)); // NOI18N
        loadingCadastro.setForeground(new java.awt.Color(255, 51, 51));
        loadingCadastro.setToolTipText("");
        loadingCadastro.setStringPainted(true);

        btnFecharAba.setBackground(new java.awt.Color(204, 0, 0));
        btnFecharAba.setFont(new java.awt.Font("Cinzel Decorative", 1, 14)); // NOI18N
        btnFecharAba.setForeground(new java.awt.Color(255, 255, 255));
        btnFecharAba.setText("X");
        btnFecharAba.setToolTipText("Voltar");
        btnFecharAba.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFecharAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharAbaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(numeroCelular))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(whatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(email)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(loadingCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(nomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(nomeUsuário, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFecharAba, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFecharAba, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeUsuário, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(whatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numeroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(loadingCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        
        //INSERT DE DADOS NA TABELA DE USUARIOS
        String sql = "INSERT INTO USUARIOS (US_ID, US_NOME, US_USUARIO, US_EMAIL, US_NASCIMENTO, US_CADASTRO, US_NUMERO, US_WHATSAPP, US_STATUS, US_SENHA) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        try {
            
            //O USO DE DOIS (PreparedStatement) DEVE-SE AO FATO DE IMPEDIR QUE UMA CONDIÇÃO ATROPELE A OUTRA
            //CADA UM VERIFICANDO SUA DETERMINADA CONDIÇÃO
            
            // VERIFICA SE O USUÁRIO JÁ EXISTE NO BANCO
            String verificarUsuario = "SELECT * FROM USUARIOS WHERE US_USUARIO = ? OR US_EMAIL = ?";
            PreparedStatement statement = getConexao.prepareStatement(verificarUsuario);
            statement.setString(1, nomeUsuário.getText());
            statement.setString(2, email.getText());
            ResultSet resultado = statement.executeQuery();
            
            //VERIFICA SE JÁ EXISTE UM ID REGISTRADO NO BANCO
            String sqlCheckEmpty = "SELECT COUNT(*) as total FROM USUARIOS";
            PreparedStatement stmtCheckEmpty = getConexao.prepareStatement(sqlCheckEmpty); 
            ResultSet resultEmpty = stmtCheckEmpty.executeQuery();
            
            
            if (resultEmpty.next()) {
                int totalRegistros = resultEmpty.getInt("total");
                
                if (totalRegistros == 0) {

                    if(resultado.next()) {
                        String mensagem = "O Usuário "+nomeUsuário.getText()+" ou Email "+email.getText()+" Já Existem, Verifique os Dados ou Faça Login!";
                        JOptionPane.showMessageDialog(null, mensagem);
                        this.dispose();
                    } else {

                        Date dataNascimento = new SimpleDateFormat("dd/MM/yyyy").parse(nascimento.getText());
                        Date cadastro = new Date();
                        char[] passwordChars = senha.getPassword();
                        String password = new String(passwordChars);

                        statement = getConexao.prepareStatement(sql);
                        statement.setInt(1, 1);
                        statement.setString(2, nomePessoa.getText());
                        statement.setString(3, nomeUsuário.getText());
                        statement.setString(4, email.getText());
                        statement.setDate(5,  new java.sql.Date(dataNascimento.getTime()));
                        statement.setDate(6, new java.sql.Date(cadastro.getTime()));
                        statement.setString(7, numeroCelular.getText());
                        statement.setString(8, whatsapp.getSelectedItem().toString());
                        statement.setString(9, "ativo");
                        statement.setString(10, password);

                        statement.executeUpdate();

                        loadingCadastro.setVisible(true);
                        loadingCadastro.setValue(0);
                        loadingCadastro.setStringPainted(true);



                        Thread thread = new Thread(() -> {
                            for (int i = 0; i <= 100; i+=10) {
                                final int progress = i; 
                                try {
                                    SwingUtilities.invokeLater(() -> loadingCadastro.setValue(progress)); 
                                    Thread.sleep(200); 
                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                }
                            }

                            JOptionPane.showMessageDialog(null, "Usuário Cadastrado, Realize o Login!");
                            this.dispose();
                        });
                            thread.start();                   
                        }

                } else {
                    //CASO JÁ EXISTA UM ID REGISTRADO, PEGA O ULTIMO ID E ADICIONA UM NOVO
                    String sqlLastID = "SELECT MAX(US_ID) as last_id FROM USUARIOS";
                    PreparedStatement stmtLastID = getConexao.prepareStatement(sqlLastID);
                    ResultSet resultSet = stmtLastID.executeQuery(sqlLastID);

                    if (resultSet.next()) {
                        int ultimoID = resultSet.getInt("last_id");
                        int novoID = ultimoID + 1;
                        
                            if(resultado.next()) {
                                String mensagem = "O Usuário "+nomeUsuário.getText()+" ou Email "+email.getText()+" Já Existem, Verifique os Dados ou Faça Login!";
                                JOptionPane.showMessageDialog(null, mensagem);
                            } else {

                                Date dataNascimento = new SimpleDateFormat("dd/MM/yyyy").parse(nascimento.getText());
                                Date cadastro = new Date();
                                char[] passwordChars = senha.getPassword();
                                String password = new String(passwordChars);

                                statement = getConexao.prepareStatement(sql);
                                statement.setInt(1, novoID);
                                statement.setString(2, nomePessoa.getText());
                                statement.setString(3, nomeUsuário.getText());
                                statement.setString(4, email.getText());
                                statement.setDate(5,  new java.sql.Date(dataNascimento.getTime()));
                                statement.setDate(6, new java.sql.Date(cadastro.getTime()));
                                statement.setString(7, numeroCelular.getText());
                                statement.setString(8, whatsapp.getSelectedItem().toString());
                                statement.setString(9, "ativo");
                                statement.setString(10, password);

                                statement.executeUpdate();

                                loadingCadastro.setVisible(true);
                                loadingCadastro.setValue(0);
                                loadingCadastro.setStringPainted(true);



                                Thread thread = new Thread(() -> {
                                    for (int i = 0; i <= 100; i+=10) {
                                        final int progress = i; 
                                        try {
                                            SwingUtilities.invokeLater(() -> loadingCadastro.setValue(progress)); 
                                            Thread.sleep(200); 
                                        } catch (InterruptedException e) {
                                            e.printStackTrace();
                                        }
                                    }

                                    JOptionPane.showMessageDialog(null, "Usuário Cadastrado, Realize o Login!");
                                    this.dispose();
                                });
                                    
                                thread.start();                   
                            }
                    }
                    
                    resultSet.close();
                    stmtLastID.close();
                }
           }
            
            resultado.close();
            statement.close();
            resultEmpty.close();
            stmtCheckEmpty.close();

            getConexao.close();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void btnFecharAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharAbaActionPerformed
        Main main = new Main(getConexao);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFecharAbaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecharAba;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JProgressBar loadingCadastro;
    private javax.swing.JTextField nascimento;
    private javax.swing.JTextField nomePessoa;
    private javax.swing.JTextField nomeUsuário;
    private javax.swing.JTextField numeroCelular;
    private javax.swing.JPasswordField senha;
    private javax.swing.JComboBox<String> whatsapp;
    // End of variables declaration//GEN-END:variables
}
